facebook<div id="nts">
            <h1><center>Quienes Somos</center> </h1>

            <div class="info">
                    <p>Barber shop, es una empresa legalmente constituida desde el año 2016, la cual nació con la finalidad de satisfacer las necesidades de hombres y mujeres a partir de los 6 meses.</p>

                    <p>Tras estudiar, desarrollar practicas al interior de la empresa y capacitarnos continuamente en asesoría de imagen y conocimiento de productos para el cuidado del cabello y la piel, nos dedicamos a realzar la imagen de nuestros consumidores, para que brillen con luz propia. Ofrecemos a nuestros clientes un servicio que se caracteriza por su excelencia en la prestación de servicios, ética empresarial, profesionalismo y un enfoque creativo para resaltar la imagen de nuestros usuarios.</p>
            </div>
        </div>

        <div id="barberos"> 
            <h1> <center> Nuestro Equipo </center> </h1> 
                    
            <div class="barbero1">
                <img class="img-responsive" src="img/team-1.jpg" alt="">
                <h3>Nombre Barbero 1<br>
                    <small>Apodo</small>
                </h3>
            </div>
                
            <div class="barbero2">
                <img class="img-responsive" src="img/team-2.jpg" alt="">
                <h3>Nombre Barbero 2 <br>
                    <small>Apodo</small>
                </h3>
            </div>

            <div class="barbero3">
                <img class="img-responsive" src="img/team-3.png" alt="">
                <h3>Nombre Barbero 3 <br>
                    <small>Apodo</small>
                </h3>
            </div>
        </div>