

<footer>
  <div id="sociales"> 
      <div class="redes">
      <ul>
        <li> <a href="https://www.facebook.com/" target="blank"> <img id="face" src="img/facebook.png" title="Encuentranos en Facebbok"> </a> </li>
      </ul>
      <ul>
        <li> <a href="https://twitter.com/?lang=es" target="blank"> <img id="twit" src="img/twitter.png" title="Siganos en twitter"> </a> </li>
      </ul>
      <ul>
        <li> <a href="https://www.instagram.com/"" target="blank" "> <img id="insa" src="img/instagram.png" title="Siganos en Instagram"> </a> </li>
      </ul>
    </div>
  </div>
  <div id="foter2"> 
	<p class="copyright">
		
	</p>

	<p class="datos">
  <font face="Camber">
  <font> Copyright © LatinosBarberShop 2016 </font> <br>
    <font>Todos los derechos reservados.</font>
		<font> <strong> Email: </strong> LatinosBarberShop@hotmail.com </font> <br>
		<font> <strong> Direccion: </strong> Carrera 78f N° 70-39 / Barrio las Ferias </font> <br>
		<font> Bogota D.c, Colombia </font>
	</p>
  </div>
</footer>

