<nav class="nav"> 
    <ul>
        <li> <a href="index.php"> Inicio</a></li>
        <li> <a href="nosotros.php"> Nosotros</a></li>
        <li> <a href="galeria.php"> Galeria</a></li>
        <li> <a href="contactenos.php"> Contactenos</a></li>
         <li> <a href="php/turnos.php"> Citas</a></li>
        <li> <a href="formulariologin.php"> Login</a></li>        
        <li> <a href="formulario_crear_cuenta.php" id="Registro"> Registro</a></li>
         
    </ul>
</nav>